[doc]
name = "thesis"
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

[[output]]
name = "thesis_expressing_crdts_with_datalog_leo_stewen"
type = "pdf"
# These are for future versions of Tectonic.
# synctex = true
# inputs = ["main.tex"]
# For now, we use this.
preamble = ""      # the preamble file to use (within `src`)
index = "main.tex" # the index file to use (within `src`)
postamble = ""     # the postamble file to use (within `src`)
