name: "Build Proposal LaTeX"
on:
  push:
    paths:
      - "proposal/**"
      - ".github/workflows/build_proposal.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Tectonic
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "2.17"
      - name: Build
        run: tectonic proposal/main.tex
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Proposal
          path: proposal/main.pdf
          if-no-files-found: error
          overwrite: true
