name: "Build Thesis LaTeX"
on:
  push:
    paths:
      - "thesis/**"
      - ".github/workflows/build_thesis.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Tectonic
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-
      - name: Setup Tectonic
        uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          biber-version: "2.17"
      - name: Build
        run: tectonic thesis/main.tex
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Thesis
          path: thesis/main.pdf
          if-no-files-found: error
          overwrite: true
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Thesis"
          files: thesis/main.pdf
